### PR TITLE
Update demo to build with nwb

### PR DESCRIPTION
**Pull request by bpugh**
Separates the demo into separate javascript and css files and enables hot reloading via nwb/webpack when running `npm start`

### CODE REVIEW

**Comment by iamdustan** [comment]
on :fire:!

**Comment by bpugh** [comment]
Thanks!
Also I noticed that you might have run the build for the latest version before updating the version number in package.json since when looking at the dist files on npmcdn they have the previous version number in the comment. Not a huge thing but might confuse some users.

**Comment by iamdustan** [comment]
Derp. You’re totally right.

screen shot 2016-03-09 at 10 00 30 pm

**Comment by bpugh** [comment]
Just thought I'd mention that the dist files still show `3.1.0` even after the `3.1.2` bump.

**Comment by iamdustan** [comment]
We removed the `dist` from git itself. Where is it showing as that?

**Pull request merged**
