### PR TITLE
#BugFix: Issue #19

### PR DESCRIPTION
**Pull request by 9jaGuy**
Doesn’t work in Google Chrome for Android

### CODE REVIEW

**Comment by iamdustan** [comment]
Merge conflicts and need a description of _why_ this fixes the issue and why it won’t break other known scenarios.

**Comment by 9jaGuy** [comment]
keypress is deprecated in place of beforeinput -> beforeedit | https://www.w3.org/TR/DOM-Level-3-Events/#event-type-keypress

**Comment by iamdustan** [comment]
will this break environments that support `keypress` but don’t have support of `beforeinput`?

**Comment by 9jaGuy** [comment]
Yes but this should work in all modern browsers.

Also binding to onKeypress will cause character duplication as I have seen in my project.

Alternative will be bind to both 'keypress' and 'beforeinput' then ignore the other event which ever one gets fired first.

**Comment by zomars** [comment]
Any resolution on this PR?

**Comment by Heymdall** [comment]
Any updates on this PR? That's strange, but can't find any info about onBeforeInput in React docs, but as I understand from [here](https://github.com/facebook/react/blob/master/src/renderers/dom/client/eventPlugins/BeforeInputEventPlugin.js) React already have fallback to keypress event for browsers, that doesn't support beforeInput event. So this PR should work in all browsers.

**Comment by 9jaGuy** [comment]
we should be good then

**Comment by iamdustan** [comment]
I'm going to release this under 3.3.0-beta.1 for folks to test and ensure there are no unintended consequences to this.

**Comment by AlexeySemin** [comment]
Doesn't work in Internet Explorer Edge

**Pull request merged**
