### PR TITLE
should close #2 and #19

### LINKED ISSUE #2: Doesnt work on android default browser
On android default browser user can input only first char. Also there problem with mobile chrome with string patterns.

### PR DESCRIPTION
**Pull request by nonmanifold**
since some android keyboards are not sending keyPress events, I added a fallback notification to parent component. 
I recommend swapping masked input with plain old unmasked one with validation.

### CODE REVIEW

**Comment by axelson** [comment]
Unfortunately this isn't working for me. Tested on Chrome 48 running on HTC One M8 running Android 5.0.1

**Comment by axelson** [comment]
Oh, nevermind I didn't realize that this requires you to pass in a new prop, then use that prop to disable react-maskedinput. The downside of this is that after you replace react-maskedinput with a new input you lose the focus on that field and the keyboard goes away.

**Comment by andre0799** [comment]
why this was never merged?

**Comment by iamdustan** [comment]
@andre0799 
1. Merge conflicts
2. https://github.com/insin/react-maskedinput/issues/23#issuecomment-194330159

**Comment by iamdustan** [comment]
I’ve seen other projects solve this problem space and am certain we can here as well. Closing this as an unsatisfactory approach.

**Pull request closed without merging**
