### PR TITLE
Replace Gulp and JSHint with ESLint/Webpack using nwb

### PR DESCRIPTION
**Pull request by bpugh**
Using nwb cli tool build project with Babel and Webpack with minimal configuration.

~~Tried using https://github.com/insin/eslint-config-jonnybuchanan for eslint but that version of babel-eslint is currently broken so I just copied that eslint configuration.~~
Update: Latest version fixes this issue.

We should probably also update the demo to follow the convention that nwb expects but wasn't sure if I should include it in this PR.

### CODE REVIEW

**Comment by iamdustan** [comment]
Dang that was fast. I’ve got a busy week yet and then I’ll get this reviewed for you. Thanks so much @bpugh

**Comment by iamdustan** [comment]
Would you have time to give this a quick attempt with nwb@0.8 and eslint-config-jonnybuchanan again? Looks solid. :clap:

**Comment by bpugh** [comment]
Sure thing!

**Comment by bpugh** [comment]
Ok I've updated the PR to use the current version of nwb and eslint-config-johnnybuchanan.
I started updating the demo to follow nwb's convention of being in `demo/src/index.js` which works well except there isn't an easy way to add the custom styles to the demo html template so hopefully I can get that in as a separate PR.

**Comment by iamdustan** [comment]
thanks you!

**Pull request merged**
